### ISSUE TITLE
how to deliver images?

### ISSUE THREAD

**Issue by duck2** [duck2/bergi#1]
bergi has lots of images, some of them displayed big(30% of the viewport), some small(~300x200).

Regardless of display, all images are served in their full size. That is not supposed to happen -- we are sending data only to be discarded in the client.

![](https://i.hizliresim.com/MarLG9.png)
current case. Only ~200KB is text and fonts.

Potential solutions:
- Use [sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail). Every image would have a small and big version. This is easier and very efficient for river and aside images but not for cover images.
- Use something like [django-imagefit](https://github.com/vinyll/django-imagefit). The issue with that is our images don't know their sizes before rendering. A client side script would have to learn the size of images and request accordingly.
- Use a thumbnailing library and [srcsets](https://cloudfour.com/thinks/responsive-images-101-part-4-srcset-width-descriptors/).
-
- Don't display images. I would really like to...

**Comment by duck2** [comment]
Following https://images.guide/ 's most basic advice and re-encoding all images with JPEG q=80 helped a lot. We currently download <800KB.

That is collecting the low-hanging fruit. Hope we won't be stuck in the [middle income trap](https://www.wikiwand.com/en/Middle_income_trap).

**Comment by oznakn** [comment]
[sorl-thumnail](https://github.com/jazzband/sorl-thumbnail) has been implemented in 9ba9cc1.
