### ISSUE TITLE
No social media share buttons in article page

### ISSUE THREAD

**Issue by duck2** [duck2/bergi#6]
We should probably make it easy for people to share our articles.

The Facebook sharer can be used like this:
```
https://www.facebook.com/sharer/sharer.php?u=<URL>
```
without introducing the FB tracker.

I am sure there are similar APIs for Twitter or LinkedIn or whatever. We can put the buttons on the [tail](https://github.com/duck2/bergi/blob/master/_bergi/templates/article.html#L14) of articles.

**Comment by ahmetburakbarakli** [comment]
I have added some buttons to share in #11. It is easier and faster to share now.

**Comment by oznakn** [comment]
Fixed with #11.
